version: "3"

services:

  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  nodeosd:
    image: gzileni/eosio:latest
    # command: nodeos --config-dir=/opt/eosio/data --data-dir=/opt/eosio/data --snapshot=/opt/eosio/data/snapshots/snapshot-0074af4e936cee1f4ab8b2f468ad42e4d1b026084c6a0c71420df990fc64b4c6.bin --hard-replay-blockchain --delete-all-blocks --verbose-http-errors --contracts-console
    command: nodeos --config-dir=/opt/eosio/data --data-dir=/opt/eosio/data --snapshot=/opt/eosio/data/snapshots/snapshot-0074af4e936cee1f4ab8b2f468ad42e4d1b026084c6a0c71420df990fc64b4c6.bin --verbose-http-errors --contracts-console --delete-all-blocks
    hostname: nodeosd
    links:
      - mongo
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./data:/opt/eosio/data

  keosd:
    image: gzileni/eosio:latest
    command: keosd --wallet-dir=/opt/eosio/wallet
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - ./wallet:/opt/eosio/wallet
